const membershipOptions = {
  "text_0": "DSA Membership",
  "text_1": "Join the national Democratic Socialists of America",
  "text_2": "none",
  "text_3": "currentColor",
  "text_4": "0 0 24 24",
  "text_5": "round",
  "text_6": "round",
  "text_7": "M5 13l4 4L19 7",
  "text_8": "National membership",
  "text_9": "with automatic Delaware chapter membership",
  "text_10": "none",
  "text_11": "currentColor",
  "text_12": "0 0 24 24",
  "text_13": "round",
  "text_14": "round",
  "text_15": "M5 13l4 4L19 7",
  "text_16": "Sliding scale dues",
  "text_17": "based on income ($27-$130 annually)",
  "text_18": "none",
  "text_19": "currentColor",
  "text_20": "0 0 24 24",
  "text_21": "round",
  "text_22": "round",
  "text_23": "M5 13l4 4L19 7",
  "text_24": "Publications",
  "text_25": "including the Democratic Left magazine",
  "text_26": "none",
  "text_27": "currentColor",
  "text_28": "0 0 24 24",
  "text_29": "round",
  "text_30": "round",
  "text_31": "M5 13l4 4L19 7",
  "text_32": "Voting rights",
  "text_33": "in Delaware DSA chapter decisions",
  "text_34": "none",
  "text_35": "currentColor",
  "text_36": "0 0 24 24",
  "text_37": "round",
  "text_38": "round",
  "text_39": "M5 13l4 4L19 7",
  "text_40": "Full participation",
  "text_41": "in national and local campaigns",
  "text_42": "https://www.example.com",
  "text_43": "_blank",
  "text_44": "noopener noreferrer",
  "text_45": "Join DSA",
  "text_46": "Dues Waiver Program",
  "text_47": "Financial assistance for membership dues",
  "text_48": "We believe that financial circumstances should never be a barrier to joining DSA. Our\n            dues waiver program provides options for those who cannot afford the standard membership\n            dues.",
  "text_49": "DSA offers reduced dues options starting at $1/month for those experiencing financial\n            hardship. Delaware DSA can also sponsor memberships for those who cannot afford any dues\n            at all.",
  "text_50": "To request a dues waiver or sponsorship from Delaware DSA, please contact us using the\n            button below.",
  "text_51": "/contact?subject=Dues%20Waiver",
  "text_52": "Request Dues Waiver"
};

export default membershipOptions;
